from __future__ import annotations

import hashlib
import json
import logging
import struct
import sys
import time
from array import array
from dataclasses import dataclass
from typing import Iterable, Sequence

import torch

from sglang.kernels.ops.speculative.dflash_snapshot_copy import (
    copy_dflash_snapshot,
    copy_dflash_snapshot_batch_packed,
)
from sglang.srt.speculative.dflash_draft_ring import DFlashDraftRingConfig

_HASH_DOMAIN = b"sglang-dflash-draft-snapshot-v1\0"
_TELEMETRY_PREFIX = "DFLASH_SNAPSHOT_TELEMETRY "
_DEFAULT_MIN_PREFIX_LENGTH = 10_208
logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class DFlashDraftSnapshotConfig:
    ring: DFlashDraftRingConfig
    min_prefix_length: int
    snapshot_rows: int
    physical_slots: int
    service_slots: int
    snapshot_base: int
    pool_size: int
    padded_tokens: int

    def slot_base(self, slot: int) -> int:
        slot = int(slot)
        if slot < 0 or slot >= self.physical_slots:
            raise ValueError(
                f"snapshot slot is outside [0, {self.physical_slots}): {slot}"
            )
        return self.snapshot_base + slot * self.snapshot_rows


def build_dflash_draft_snapshot_config(
    ring: DFlashDraftRingConfig,
    *,
    min_prefix_length: int = _DEFAULT_MIN_PREFIX_LENGTH,
    physical_slots: int = 21,
    service_slots: int = 20,
) -> DFlashDraftSnapshotConfig:
    min_prefix_length = int(min_prefix_length)
    physical_slots = int(physical_slots)
    service_slots = int(service_slots)
    if min_prefix_length <= 0 or min_prefix_length % int(ring.page_size):
        raise ValueError(
            "min_prefix_length must be positive and page aligned: "
            f"prefix={min_prefix_length}, page={ring.page_size}"
        )
    if physical_slots <= 0:
        raise ValueError("physical_slots must be positive")
    if service_slots <= 0 or service_slots >= physical_slots:
        raise ValueError(
            "service_slots must be positive and leave a publication reserve: "
            f"service={service_slots}, physical={physical_slots}"
        )

    # A radix snapshot is published at a page-aligned boundary. At that exact
    # boundary the compact suffix is ceil(window/page)*page; the later
    # non-aligned residue is regenerated by ordinary prefill.
    snapshot_rows = (
        (int(ring.window_size) + int(ring.page_size) - 1) // int(ring.page_size)
    ) * int(ring.page_size)
    snapshot_base = int(ring.padded_tokens)
    padded_tokens = snapshot_base + physical_slots * snapshot_rows
    pool_size = padded_tokens - int(ring.page_size)
    return DFlashDraftSnapshotConfig(
        ring=ring,
        min_prefix_length=min_prefix_length,
        snapshot_rows=snapshot_rows,
        physical_slots=physical_slots,
        service_slots=service_slots,
        snapshot_base=snapshot_base,
        pool_size=pool_size,
        padded_tokens=padded_tokens,
    )


@dataclass(frozen=True, order=True)
class DFlashSnapshotKey:
    prefix_length: int
    digest: bytes


@dataclass(frozen=True)
class DFlashSnapshotHandle:
    key: DFlashSnapshotKey
    slot: int
    slot_generation: int
    cache_generation: int
    valid_rows: int


@dataclass(frozen=True)
class DFlashSnapshotPublication:
    key: DFlashSnapshotKey
    handle: DFlashSnapshotHandle | None
    victim: DFlashSnapshotHandle | None
    action: str
    reason: str | None = None

    @property
    def copy_required(self) -> bool:
        return self.action == "copy"


@dataclass(frozen=True)
class DFlashSnapshotMatchPlan:
    status: str
    handle: DFlashSnapshotHandle | None
    normal_boundary: int
    full_boundary: int
    selected_boundary: int | None
    delta: int | None


@dataclass
class _SnapshotSlot:
    generation: int = 0
    state: str = "free"
    key: DFlashSnapshotKey | None = None
    valid_rows: int = 0
    refcount: int = 0
    last_used: int = 0


def _token_bytes(token_ids: Sequence[int]) -> tuple[memoryview, object]:
    if sys.byteorder != "little":
        raise RuntimeError("DFlash snapshot hashing requires little-endian token bytes")
    if isinstance(token_ids, array) and token_ids.typecode == "q":
        owner: object = token_ids
    else:
        owner = array("q", (int(token) for token in token_ids))
    view = memoryview(owner).cast("B")
    return view, owner


def build_dflash_snapshot_keys(
    token_ids: Sequence[int],
    boundaries: Iterable[int],
    *,
    namespace: str,
    extra_key: str | None,
    cache_generation: int,
) -> dict[int, DFlashSnapshotKey]:
    """Hash many prefix boundaries with one linear pass over canonical int64 IDs."""

    ordered = sorted({int(boundary) for boundary in boundaries})
    if not ordered:
        return {}
    if ordered[0] < 0 or ordered[-1] > len(token_ids):
        raise ValueError(
            f"snapshot boundary outside token sequence: {ordered[0]}..{ordered[-1]} "
            f"for {len(token_ids)} tokens"
        )

    namespace_bytes = namespace.encode("utf-8")
    extra_bytes = b"" if extra_key is None else extra_key.encode("utf-8")
    digest = hashlib.sha256(_HASH_DOMAIN)
    digest.update(struct.pack("<Q", len(namespace_bytes)))
    digest.update(namespace_bytes)
    digest.update(b"\x00" if extra_key is None else b"\x01")
    digest.update(struct.pack("<Q", len(extra_bytes)))
    digest.update(extra_bytes)
    digest.update(struct.pack("<Q", int(cache_generation)))

    raw, owner = _token_bytes(token_ids)
    del owner  # The memoryview retains its exporter.
    cursor = 0
    result: dict[int, DFlashSnapshotKey] = {}
    for boundary in ordered:
        digest.update(raw[cursor * 8 : boundary * 8])
        at_boundary = digest.copy()
        at_boundary.update(struct.pack("<Q", boundary))
        result[boundary] = DFlashSnapshotKey(
            prefix_length=boundary,
            digest=at_boundary.digest(),
        )
        cursor = boundary
    return result


class DFlashDraftSnapshotDirectory:
    """Single-threaded, deterministic two-phase directory for physical slots."""

    def __init__(
        self,
        config: DFlashDraftSnapshotConfig,
        *,
        namespace: str,
        emit_telemetry: bool = True,
    ):
        if not namespace:
            raise ValueError("snapshot namespace must be non-empty")
        self.config = config
        self.namespace = namespace
        self._emit_telemetry = bool(emit_telemetry)
        self.cache_generation = 0
        self._clock = 0
        self._slots = [_SnapshotSlot() for _ in range(config.physical_slots)]
        self._resident: dict[DFlashSnapshotKey, DFlashSnapshotHandle] = {}
        self._pending: dict[DFlashSnapshotKey, DFlashSnapshotHandle] = {}
        self._request_refs: dict[str, DFlashSnapshotHandle] = {}

    def _tick(self) -> int:
        self._clock += 1
        return self._clock

    def _telemetry_enabled(self) -> bool:
        if not self._emit_telemetry:
            return False
        # Runtime import avoids an environ -> scheduler -> snapshot import
        # cycle during process initialization.
        from sglang.srt.environ import envs

        return envs.SGLANG_OMNIVA_DFLASH_DRAFT_SNAPSHOT_TELEMETRY.get()

    def _log_telemetry(self, event: str, **fields) -> None:
        if not self._telemetry_enabled():
            return
        logger.info(
            "%s%s",
            _TELEMETRY_PREFIX,
            json.dumps(
                {
                    "schema_version": 1,
                    "event": event,
                    "monotonic_ns": time.perf_counter_ns(),
                    **fields,
                },
                sort_keys=True,
                separators=(",", ":"),
            ),
        )

    def make_keys(
        self,
        token_ids: Sequence[int],
        boundaries: Iterable[int],
        *,
        extra_key: str | None,
    ) -> dict[int, DFlashSnapshotKey]:
        return build_dflash_snapshot_keys(
            token_ids,
            boundaries,
            namespace=self.namespace,
            extra_key=extra_key,
            cache_generation=self.cache_generation,
        )

    def make_key(
        self,
        token_ids: Sequence[int],
        boundary: int,
        *,
        extra_key: str | None,
    ) -> DFlashSnapshotKey:
        return self.make_keys(token_ids, [boundary], extra_key=extra_key)[int(boundary)]

    def find_tentative(
        self,
        token_ids: Sequence[int],
        *,
        extra_key: str | None,
        normal_boundary: int,
        full_boundary: int,
        max_delta: int,
        key_cache: dict[int, DFlashSnapshotKey] | None = None,
    ) -> DFlashSnapshotHandle | None:
        normal_boundary = int(normal_boundary)
        full_boundary = int(full_boundary)
        max_delta = int(max_delta)
        if (
            full_boundary <= normal_boundary
            or full_boundary < self.config.min_prefix_length
            or max_delta < 0
        ):
            return None

        boundaries = {
            key.prefix_length
            for key in self._resident
            if self.config.min_prefix_length <= key.prefix_length <= full_boundary
            and normal_boundary < key.prefix_length
            and full_boundary - key.prefix_length <= max_delta
        }
        keys = {
            boundary: key_cache[boundary]
            for boundary in boundaries
            if key_cache is not None and boundary in key_cache
        }
        missing = boundaries - keys.keys()
        if missing:
            computed = self.make_keys(token_ids, missing, extra_key=extra_key)
            keys.update(computed)
            if key_cache is not None:
                key_cache.update(computed)
        for boundary in sorted(boundaries, reverse=True):
            handle = self._resident.get(keys[boundary])
            if handle is not None and self._handle_is_resident(handle):
                return handle
        return None

    def begin_publish(
        self, key: DFlashSnapshotKey, *, valid_rows: int
    ) -> DFlashSnapshotPublication:
        valid_rows = int(valid_rows)
        if key.prefix_length < self.config.min_prefix_length:
            raise ValueError(
                "snapshot publication boundary is below min_prefix_length: "
                f"boundary={key.prefix_length}, "
                f"minimum={self.config.min_prefix_length}"
            )
        if key.prefix_length % self.config.ring.page_size:
            raise ValueError("snapshot publication boundary must be page aligned")
        if valid_rows != min(key.prefix_length, self.config.snapshot_rows):
            raise ValueError(
                "snapshot valid_rows must be the exact aligned suffix length: "
                f"valid={valid_rows}, prefix={key.prefix_length}, "
                f"snapshot_rows={self.config.snapshot_rows}"
            )

        existing = self._resident.get(key)
        if existing is not None and self._handle_is_resident(existing):
            self._slots[existing.slot].last_used = self._tick()
            return DFlashSnapshotPublication(
                key=key, handle=existing, victim=None, action="existing"
            )
        if key in self._pending:
            return DFlashSnapshotPublication(
                key=key,
                handle=None,
                victim=None,
                action="skip",
                reason="duplicate_pending",
            )

        resident_count = len(self._resident)
        victim: DFlashSnapshotHandle | None = None
        if resident_count >= self.config.service_slots:
            candidates = [
                (slot.last_used, slot_id, slot)
                for slot_id, slot in enumerate(self._slots)
                if slot.state == "resident" and slot.refcount == 0
            ]
            if not candidates:
                return DFlashSnapshotPublication(
                    key=key,
                    handle=None,
                    victim=None,
                    action="skip",
                    reason="all_residents_pinned",
                )
            _, victim_slot_id, victim_slot = min(candidates)
            assert victim_slot.key is not None
            victim = DFlashSnapshotHandle(
                key=victim_slot.key,
                slot=victim_slot_id,
                slot_generation=victim_slot.generation,
                cache_generation=self.cache_generation,
                valid_rows=victim_slot.valid_rows,
            )

        free_slots = [
            slot_id for slot_id, slot in enumerate(self._slots) if slot.state == "free"
        ]
        if not free_slots:
            return DFlashSnapshotPublication(
                key=key,
                handle=None,
                victim=victim,
                action="skip",
                reason="publication_reserve_busy",
            )
        slot_id = min(free_slots)
        slot = self._slots[slot_id]
        slot.generation += 1
        slot.state = "staging"
        slot.key = key
        slot.valid_rows = valid_rows
        slot.refcount = 0
        slot.last_used = self._tick()
        handle = DFlashSnapshotHandle(
            key=key,
            slot=slot_id,
            slot_generation=slot.generation,
            cache_generation=self.cache_generation,
            valid_rows=valid_rows,
        )
        self._pending[key] = handle
        return DFlashSnapshotPublication(
            key=key, handle=handle, victim=victim, action="copy"
        )

    def commit_publish(
        self, publication: DFlashSnapshotPublication
    ) -> DFlashSnapshotHandle:
        if not publication.copy_required or publication.handle is None:
            raise ValueError("only a copy publication can be committed")
        handle = publication.handle
        slot = self._slots[handle.slot]
        if (
            handle.cache_generation != self.cache_generation
            or slot.state != "staging"
            or slot.generation != handle.slot_generation
            or slot.key != handle.key
            or self._pending.get(handle.key) != handle
        ):
            raise RuntimeError("stale or mismatched snapshot publication commit")

        victim = publication.victim
        if victim is not None:
            victim_slot = self._slots[victim.slot]
            if not self._handle_is_resident(victim) or victim_slot.refcount != 0:
                raise RuntimeError("snapshot victim changed while publication staged")
            if self._resident.get(victim.key) != victim:
                raise RuntimeError("snapshot victim directory mapping drifted")
            del self._resident[victim.key]
            victim_slot.state = "free"
            victim_slot.key = None
            victim_slot.valid_rows = 0
            victim_slot.last_used = self._tick()

        del self._pending[handle.key]
        slot.state = "resident"
        slot.last_used = self._tick()
        self._resident[handle.key] = handle
        if len(self._resident) > self.config.service_slots:
            raise AssertionError("snapshot resident count exceeded service capacity")
        return handle

    def abort_publish(self, publication: DFlashSnapshotPublication) -> None:
        if not publication.copy_required or publication.handle is None:
            return
        handle = publication.handle
        slot = self._slots[handle.slot]
        if self._pending.get(handle.key) == handle:
            del self._pending[handle.key]
        if slot.state == "staging" and slot.generation == handle.slot_generation:
            slot.state = "free"
            slot.key = None
            slot.valid_rows = 0
            slot.refcount = 0
            slot.last_used = self._tick()

    def acquire_for_request(
        self, handle: DFlashSnapshotHandle, *, request_id: str
    ) -> DFlashSnapshotHandle | None:
        current = self._request_refs.get(request_id)
        if current is not None:
            if current != handle:
                raise RuntimeError("request attempted to acquire two snapshot handles")
            return current
        if not self._handle_is_resident(handle):
            return None
        slot = self._slots[handle.slot]
        slot.refcount += 1
        slot.last_used = self._tick()
        self._request_refs[request_id] = handle
        return handle

    def release_request(self, request_id: str) -> bool:
        handle = self._request_refs.pop(request_id, None)
        if handle is None:
            return False
        slot = self._slots[handle.slot]
        if not self._handle_is_resident(handle) or slot.refcount <= 0:
            raise RuntimeError("snapshot request release found stale refcount state")
        slot.refcount -= 1
        slot.last_used = self._tick()
        if self._telemetry_enabled():
            self._log_telemetry(
                "release",
                request_id=request_id,
                slot=handle.slot,
                slot_generation=handle.slot_generation,
                handle_cache_generation=handle.cache_generation,
                **self.stats(),
            )
        return True

    def reset(self) -> None:
        if self._request_refs or self._pending:
            raise RuntimeError("snapshot reset requires zero references and no staging")
        if any(slot.refcount for slot in self._slots):
            raise RuntimeError("snapshot reset found a leaked slot reference")
        self.cache_generation += 1
        self._resident.clear()
        for slot in self._slots:
            slot.state = "free"
            slot.key = None
            slot.valid_rows = 0
            slot.refcount = 0
            slot.last_used = self._tick()
        if self._telemetry_enabled():
            self._log_telemetry("reset", **self.stats())

    def stats(self) -> dict[str, int]:
        return {
            "cache_generation": self.cache_generation,
            "resident": len(self._resident),
            "pending": len(self._pending),
            "request_refs": len(self._request_refs),
            "free": sum(slot.state == "free" for slot in self._slots),
            "pinned": sum(slot.refcount > 0 for slot in self._slots),
        }

    def rank_agreement_signature(self) -> tuple:
        """Return the complete deterministic state used by batch publication.

        Publication selects free slots and zero-reference LRU victims from
        this state. Comparing it together with an ordered candidate batch on
        every TP rank proves that subsequent local publication decisions are
        identical without a data-dependent collective per request.
        """

        def key_signature(key: DFlashSnapshotKey | None):
            return None if key is None else (key.prefix_length, key.digest)

        def handle_signature(handle: DFlashSnapshotHandle):
            return (
                key_signature(handle.key),
                handle.slot,
                handle.slot_generation,
                handle.cache_generation,
                handle.valid_rows,
            )

        return (
            self.cache_generation,
            self._clock,
            tuple(
                (
                    slot.generation,
                    slot.state,
                    key_signature(slot.key),
                    slot.valid_rows,
                    slot.refcount,
                    slot.last_used,
                )
                for slot in self._slots
            ),
            tuple(
                sorted(
                    (key_signature(key), handle_signature(handle))
                    for key, handle in self._resident.items()
                )
            ),
            tuple(
                sorted(
                    (key_signature(key), handle_signature(handle))
                    for key, handle in self._pending.items()
                )
            ),
            tuple(
                sorted(
                    (request_id, handle_signature(handle))
                    for request_id, handle in self._request_refs.items()
                )
            ),
        )

    def _handle_is_resident(self, handle: DFlashSnapshotHandle) -> bool:
        if handle.cache_generation != self.cache_generation:
            return False
        if handle.slot < 0 or handle.slot >= len(self._slots):
            return False
        slot = self._slots[handle.slot]
        return (
            slot.state == "resident"
            and slot.generation == handle.slot_generation
            and slot.key == handle.key
            and slot.valid_rows == handle.valid_rows
        )


class DFlashDraftSnapshotStore:
    """Physical BF16 snapshot copy facade over the qualified DFlash MHA pool."""

    def __init__(self, kv_pool, config: DFlashDraftSnapshotConfig):
        self.kv_pool = kv_pool
        self.config = config
        if (
            config.physical_slots > 32
            or config.ring.request_rows > 16
            or config.ring.ring_pages > 128
            or config.snapshot_rows > 4095
        ):
            raise RuntimeError("DFlash snapshot packed-metadata contract overflow")
        buffers = [*kv_pool.k_buffer, *kv_pool.v_buffer]
        if len(buffers) != 12:
            raise RuntimeError(
                f"DFlash snapshot store requires 12 K/V buffers, got {len(buffers)}"
            )
        first = buffers[0]
        if first.dtype != torch.bfloat16:
            raise RuntimeError(
                f"DFlash snapshot store requires BF16, got {first.dtype}"
            )
        if getattr(kv_pool, "kv_cache_layout", "nhd") != "nhd":
            raise RuntimeError("DFlash snapshot store requires the NHD KV layout")
        if int(kv_pool.size) != config.pool_size:
            raise RuntimeError(
                "DFlash snapshot pool size mismatch: "
                f"actual={kv_pool.size}, expected={config.pool_size}"
            )
        for buffer in buffers:
            if (
                buffer.dtype != first.dtype
                or buffer.device != first.device
                or int(buffer.shape[0]) != config.padded_tokens
                or not buffer.is_contiguous()
                or int(buffer[0].numel()) != int(first[0].numel())
            ):
                raise RuntimeError("DFlash snapshot KV buffer contract drifted")
        self.device = first.device
        self.row_elements = int(first[0].numel())
        self.buffer_ptrs = torch.tensor(
            [buffer.data_ptr() for buffer in buffers],
            dtype=torch.int64,
            device=self.device,
        )
        self._ready_events = [torch.cuda.Event() for _ in range(config.physical_slots)]
        self._slot_ready = [False] * config.physical_slots

    def _copy(
        self,
        items: Sequence[tuple[DFlashSnapshotHandle, int, int]],
        *,
        snapshot_to_ring: bool,
    ) -> None:
        if not items:
            return
        if len(items) > 8:
            raise RuntimeError("DFlash snapshot copy supports at most eight requests")
        snapshot_bases = []
        ring_bases = []
        ring_start_pages = []
        valid_rows = []
        for handle, request_pool_index, boundary in items:
            boundary = int(boundary)
            if boundary != handle.key.prefix_length:
                raise RuntimeError(
                    "snapshot copy boundary does not match its content key: "
                    f"copy={boundary}, key={handle.key.prefix_length}"
                )
            if boundary % self.config.ring.page_size:
                raise RuntimeError("snapshot copy boundary must be page aligned")
            request_pool_index = int(request_pool_index)
            if (
                request_pool_index < 0
                or request_pool_index >= self.config.ring.request_rows
            ):
                raise RuntimeError(
                    f"snapshot request row outside allocation: {request_pool_index}"
                )
            absolute_start = boundary - handle.valid_rows
            snapshot_bases.append(self.config.slot_base(handle.slot))
            ring_bases.append(
                self.config.ring.page_size
                + request_pool_index * self.config.ring.row_stride
            )
            ring_start_pages.append(
                (absolute_start // self.config.ring.page_size)
                % self.config.ring.ring_pages
            )
            valid_rows.append(handle.valid_rows)

        if len(items) == 1:
            copy_dflash_snapshot(
                buffer_ptrs=self.buffer_ptrs,
                snapshot_base=snapshot_bases[0],
                ring_base=ring_bases[0],
                ring_start_page=ring_start_pages[0],
                valid_rows=valid_rows[0],
                row_elements=self.row_elements,
                page_size=self.config.ring.page_size,
                ring_pages=self.config.ring.ring_pages,
                snapshot_to_ring=snapshot_to_ring,
            )
            return

        # One uint32 launch scalar per request avoids four tiny H2D tensors:
        # [valid_rows:12][ring_start_page:7][request_row:4][snapshot_slot:5].
        packed_metadata = [
            int(handle.slot)
            | (int(request_pool_index) << 5)
            | (int(ring_start_page) << 9)
            | (int(rows) << 16)
            for (handle, request_pool_index, _), ring_start_page, rows in zip(
                items, ring_start_pages, valid_rows
            )
        ]
        copy_dflash_snapshot_batch_packed(
            buffer_ptrs=self.buffer_ptrs,
            packed_metadata=packed_metadata,
            max_rows=max(valid_rows),
            snapshot_base=self.config.snapshot_base,
            snapshot_rows=self.config.snapshot_rows,
            row_stride=self.config.ring.row_stride,
            row_elements=self.row_elements,
            page_size=self.config.ring.page_size,
            ring_pages=self.config.ring.ring_pages,
            snapshot_to_ring=snapshot_to_ring,
        )

    def publish(
        self,
        publication: DFlashSnapshotPublication,
        *,
        request_pool_index: int,
    ) -> None:
        if not publication.copy_required or publication.handle is None:
            raise ValueError("physical publication requires a copy decision")
        self._copy(
            [
                (
                    publication.handle,
                    request_pool_index,
                    publication.key.prefix_length,
                )
            ],
            snapshot_to_ring=False,
        )
        self._ready_events[publication.handle.slot].record(
            torch.cuda.current_stream(self.device)
        )
        self._slot_ready[publication.handle.slot] = True

    def restore(self, items: Sequence[tuple[DFlashSnapshotHandle, int, int]]) -> None:
        stream = torch.cuda.current_stream(self.device)
        for handle, _, _ in items:
            if not self._slot_ready[handle.slot]:
                raise RuntimeError(
                    "snapshot restore observed an unpublished physical slot"
                )
            stream.wait_event(self._ready_events[handle.slot])
        self._copy(items, snapshot_to_ring=True)

    def reset(self) -> None:
        self._slot_ready = [False] * self.config.physical_slots


def match_prefix_with_dflash_snapshot(
    *,
    tree_cache,
    req,
    token_ids,
    base_key_limit: int | None,
    cow_mamba: bool,
    include_req: bool,
    acquire: bool,
):
    """Run one tentative capped match and an atomic ordinary-ring fallback."""

    from sglang.srt.environ import envs
    from sglang.srt.mem_cache.base_prefix_cache import (
        MatchPrefixParams,
        zero_match_result,
    )
    from sglang.srt.mem_cache.radix_cache import RadixKey

    match_started_ns = (
        time.perf_counter_ns()
        if acquire and envs.SGLANG_OMNIVA_DFLASH_DRAFT_SNAPSHOT_TELEMETRY.get()
        else None
    )
    directory = tree_cache.dflash_snapshot_directory()
    if directory is None:
        raise RuntimeError("DFlash snapshot matching requires a registered directory")
    if tree_cache.__class__.__name__ != "RadixCache":
        raise RuntimeError("DFlash snapshot matching requires the qualified RadixCache")

    token_count = len(token_ids)
    full_limit = (
        token_count
        if base_key_limit is None
        else min(token_count, max(0, int(base_key_limit)))
    )
    reprefill_tail = int(tree_cache.reprefill_tail_tokens())
    normal_limit = min(full_limit, max(0, token_count - reprefill_tail))
    page_size = int(directory.config.ring.page_size)
    full_boundary = full_limit // page_size * page_size
    normal_boundary = normal_limit // page_size * page_size
    max_delta = envs.SGLANG_OMNIVA_DFLASH_DRAFT_SNAPSHOT_MAX_DELTA.get()
    # A request is append-only by contract. Reuse content keys between the
    # scheduling preview and final admission even though each may materialize
    # a different array object with the same token content.
    key_cache_tag = (
        len(token_ids),
        req.extra_key,
        directory.cache_generation,
        directory.namespace,
    )
    cached = getattr(req, "_dflash_snapshot_key_cache", None)
    if cached is None or cached[0] != key_cache_tag:
        cached = (key_cache_tag, {})
        req._dflash_snapshot_key_cache = cached
    tentative = directory.find_tentative(
        token_ids,
        extra_key=req.extra_key,
        normal_boundary=normal_boundary,
        full_boundary=full_boundary,
        max_delta=max_delta,
        key_cache=cached[1],
    )

    def run_match(limit: int):
        result = tree_cache.match_prefix(
            MatchPrefixParams(
                key=RadixKey(
                    token_ids=token_ids,
                    extra_key=req.extra_key,
                    limit=limit,
                ),
                cow_mamba=cow_mamba,
                req=req if include_req else None,
            )
        )
        if envs.SGLANG_RADIX_FORCE_MISS.get():
            result = zero_match_result(tree_cache, result, extra_key=req.extra_key)
        return result

    if tentative is None:
        result = run_match(normal_limit)
        plan = DFlashSnapshotMatchPlan(
            status="ordinary_replay",
            handle=None,
            normal_boundary=normal_boundary,
            full_boundary=full_boundary,
            selected_boundary=None,
            delta=None,
        )
    else:
        result = run_match(tentative.key.prefix_length)
        validated = (
            not envs.SGLANG_RADIX_FORCE_MISS.get()
            and len(result.device_indices) == tentative.key.prefix_length
        )
        acquired = (
            directory.acquire_for_request(tentative, request_id=req.rid)
            if validated and acquire
            else tentative
            if validated
            else None
        )
        if acquired is None:
            # RadixCache.match_prefix does not acquire a node ref. The fallback
            # therefore needs no lock mutation and completes in this same call.
            result = run_match(normal_limit)
            plan = DFlashSnapshotMatchPlan(
                status=(
                    "target_validation_failed"
                    if not validated
                    else "snapshot_acquire_failed"
                ),
                handle=None,
                normal_boundary=normal_boundary,
                full_boundary=full_boundary,
                selected_boundary=tentative.key.prefix_length,
                delta=full_boundary - tentative.key.prefix_length,
            )
        else:
            plan = DFlashSnapshotMatchPlan(
                status="snapshot_selected",
                handle=acquired,
                normal_boundary=normal_boundary,
                full_boundary=full_boundary,
                selected_boundary=tentative.key.prefix_length,
                delta=full_boundary - tentative.key.prefix_length,
            )

    req.dflash_snapshot_match_plan = plan
    if acquire:
        req.dflash_snapshot_handle = plan.handle
        # A retracted request can be admitted again with a new final match.
        # Each admission owns one restore/fallback decision event.
        req.dflash_snapshot_telemetry_emitted = False
        req.dflash_snapshot_match_duration_ns = (
            None
            if match_started_ns is None
            else time.perf_counter_ns() - match_started_ns
        )
        # The cache exists only to share hashing work between the scheduling
        # preview and final admission. Retractions can rebuild a request at a
        # previously seen length with different output tokens, so carrying
        # content keys beyond final admission would make length-only reuse
        # unsafe across request rounds.
        req._dflash_snapshot_key_cache = None
    return result
